In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Sequential

# Define the 5x5 input matrix
input_matrix = np.array([[1, 2, 3, 4, 5],
                         [6, 7, 8, 9, 10],
                         [11, 12, 13, 14, 15],
                         [16, 17, 18, 19, 20],
                         [21, 22, 23, 24, 25]], dtype=np.float32)



# Define a 3x3 kernel
kernel = np.array([[0, 1, 0],
                   [1, -4, 1],
                   [0, 1, 0]], dtype=np.float32).reshape((3, 3, 1, 1))

kernel=tf.constant(kernel)
output_tensor1 = tf.nn.conv2d(
    input=input_tensor,
    filters=kernel,
    strides=1,  # Move 1 pixel at a time
    padding='VALID'
)
output_tensor2 = tf.nn.conv2d(
    input=input_tensor,
    filters=kernel,
    strides=2,  # Move 2 pixel at a time
    padding='VALID'
)
output_tensor3 = tf.nn.conv2d(
    input=input_tensor,
    filters=kernel,
    strides=1,  # Move 1 pixel at a time
    padding='SAME'
)
output_tensor4 = tf.nn.conv2d(
    input=input_tensor,
    filters=kernel,
    strides=2,  # Move 2 pixel at a time
    padding='SAME'
)



# Print the output tensor
print('\n	Stride = 1, Padding = ‘VALID’ :\n',output_tensor1)
print('\n	Stride = 2, Padding = ‘VALID’ :\n',output_tensor2)
print('\n	Stride = 1, Padding = ‘SAME’ :\n',output_tensor3)
print('\n	Stride = 2, Padding = ‘SAME’ :\n',output_tensor4)



	Stride = 1, Padding = ‘VALID’ :
 tf.Tensor(
[[[[0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]]]], shape=(1, 3, 3, 1), dtype=float32)

	Stride = 2, Padding = ‘VALID’ :
 tf.Tensor(
[[[[0.]
   [0.]]

  [[0.]
   [0.]]]], shape=(1, 2, 2, 1), dtype=float32)

	Stride = 1, Padding = ‘SAME’ :
 tf.Tensor(
[[[[  4.]
   [  3.]
   [  2.]
   [  1.]
   [ -6.]]

  [[ -5.]
   [  0.]
   [  0.]
   [  0.]
   [-11.]]

  [[-10.]
   [  0.]
   [  0.]
   [  0.]
   [-16.]]

  [[-15.]
   [  0.]
   [  0.]
   [  0.]
   [-21.]]

  [[-46.]
   [-27.]
   [-28.]
   [-29.]
   [-56.]]]], shape=(1, 5, 5, 1), dtype=float32)

	Stride = 2, Padding = ‘SAME’ :
 tf.Tensor(
[[[[  4.]
   [  2.]
   [ -6.]]

  [[-10.]
   [  0.]
   [-16.]]

  [[-46.]
   [-28.]
   [-56.]]]], shape=(1, 3, 3, 1), dtype=float32)
